### ISSUE TITLE
should openidc_validate_id_token use openidc.jwt_verify ?

### ISSUE THREAD

**Issue by bodewig** [pingidentity/lua-resty-openidc#102]
Before I create a PR (actually, before I even start working on a PR :-) I thought I better ask.

Right now `openidc_validate_id_token` validates the id token while `openidc.jwt_verify` is the entry point for access token verifications for users that know their access tokens are JWTs. They contain some similar verifications (see the `exp` claim but are not entirely the same.

`openidc_validate_id_token` contains additional verifications that are specific to id tokens but could be re-written as "claim specs" to use with `jwt:verify`. Also right now the code doesn't verify the id token's signature at all and would fail for encrypted id tokens, I think we'd get both from using `openidc.jwt_verify` when verifying the id token.

**Comment by zandbelt** [comment]
I'm a bit hesitant about using "claim specs" because I remember that earlier versions of lua-resty-jwt weren't offering what would be needed (I believe that may have changed at some point) and later ones contained some bugs in the implementation. Using it would probably require a certain relatively recent lua-resty-jwt version dependency, not sure if the benefit of the former is worth the restriction of the latter (yet).

Signature validation with RSA keys obtained from a JWKs URI, which is the default for OpenID Connect, is not supported by lua-resty-jwt. I'm working on it in a branch here:
https://github.com/pingidentity/lua-resty-openidc/tree/support-rsa-kty-jwks
Encryption is not supported anywhere AFAICT (perhaps only with symmetric keys).

So I'm not in favor at this point in time, but perhaps you have more insights.

**Comment by bodewig** [comment]
I've been looking at the lua-resty-jwt master branch and am not sure what works with what version. So far I've used claim specs successfully (using the last released version) but you'll certainly have more experience with it than I have.

`jwt:load_jwt` can decrypt a JWE - and the current code would do so successfully unless a pre-shared key was required (the second parameter is always `nil` right now). This means that `openidc.jwt_verify` may be able to deal with some JWEs, while `openidc_authorization_response` never does.

What I really wanted to achieve was to extract the common functionality of the two JWT validating pieces. If you don't trust claim specs, we could still have `openidc_authorization_response` use `jwt:load_jwt` in place of the custom parsing - using `jwt:verify` here would be beneficial once it works for all RSA keys as well.

[BTW, I've been using #82 in a local fork and it seems to work fine, am looking forward to you merging your branch]

**Comment by zandbelt** [comment]
Ok, now I'm starting to understand what you're getting at but: the access token in an OIDC flow is not meant to be validated by the Client. It is meant to be validated by the Resource Server which is e.g. the UserInfo endpoint in OIDC or some other API.

In an OIDC flow the RP (lua-resty-openidc) should treat the access token as opaque and just use to towards APIs. And I believe that is the case today: there's no call to load_jwt or custom parsing in that "leg". So no need to harmonize.

**Comment by zandbelt** [comment]
Wrt: #82: I believe it could use some cleanup and I wanted some more time to do that. Of course you're free to cleanup yourself and I'll pull ;-)

**Comment by bodewig** [comment]
In my case I am the client and (the API gateway of) the resource server. :-)

I've been talking about the custom parsing of the id token, though. The lines following https://github.com/pingidentity/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L379 could be replaced by `jwt:load_jwt` and `verify` could be used to verify the signature here as well.
