### ISSUE TITLE
Session management in RP

### ISSUE THREAD

**Issue by sureshvarman** [pingidentity/lua-resty-openidc#88]
Is session expiration completely depends on **OP**. Because even when i have my session_cookie_lifetime set to 3600, the user is still able to visit the application after 1 hour because the session in **OP**, is not expired. how to handle the expire the session in **RP** itself.

**Comment by zandbelt** [comment]
Apparently the OP has an SSO session that lasts longer than 1 hour. After 1 hour the RP would send the user to the OP and since there's a valid session there, the user would be authenticated and returned to the RP without explicit interaction. The point of SSO is to use that session to authenticate users so there's nothing else you can do than reducing the lifetime of that session at the OP.

**Comment by sureshvarman** [comment]
Thanks @zandbelt, i already did that, but curious to know for any ways in RP itself.

**Comment by zandbelt** [comment]
one could synchronize sessions between RP and OP by implementing something like http://openid.net/specs/openid-connect-session-1_0.html on both sides
